name: check dotnet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Visualizza versione .NET
        run: dotnet --version
      
      - name: Visualizza tutte le versioni .NET installate
        run: dotnet --list-sdks
      
      - name: Visualizza versione dei runtime .NET
        run: dotnet --list-runtimes